// Color-season and body-shape knowledge base, ported from HerStyleVault's
// internal analysis tools. Used to ground the AI report generator with
// factual, tested styling data instead of letting the model invent it.

function computeColorAxes(a) {
  let warmScore = 0, coolScore = 0;
  if (a.jewelry === 'gold') warmScore += 2;
  if (a.jewelry === 'silver') coolScore += 2;
  if (a.jewelry === 'both') { warmScore++; coolScore++; }
  if (a.sun === 'tan') warmScore += 2;
  if (a.sun === 'burn') coolScore += 2;
  if (a.sun === 'both') { warmScore++; coolScore++; }
  if (a.veins === 'green') warmScore += 2;
  if (a.veins === 'blue') coolScore += 2;
  if (a.veins === 'both') { warmScore++; coolScore++; }
  if (a.comp === 'warm') warmScore += 2;
  if (a.comp === 'cool') coolScore += 2;
  if (a.wash === 'cool') warmScore++;
  if (a.wash === 'warm') coolScore++;
  const net = warmScore - coolScore;
  const undertone = net >= 3 ? 'warm' : net <= -3 ? 'cool' : 'neutral';
  const depthScore = { fair: 0, medium: 1, tan: 2, deep: 3 }[a.depth] ?? 1;
  const value = depthScore === 0 ? 'light' : depthScore === 3 ? 'deep' : 'medium';
  let chromaScore = 0;
  if (a.chroma === 'bright') chromaScore += 2;
  if (a.chroma === 'muted') chromaScore -= 2;
  if (a.contrast === 'high') chromaScore += 1;
  if (a.contrast === 'low') chromaScore -= 1;
  const chroma = chromaScore >= 1 ? 'bright' : chromaScore <= -1 ? 'soft' : 'blended';
  return { undertone, value, chroma };
}

const SEASON_TABLE = {
  warm: { bright: { light: 'lightSpring', medium: 'trueSpring', deep: 'brightSpring' }, soft: { light: 'softAutumn', medium: 'trueAutumn', deep: 'deepAutumn' }, blended: { light: 'lightSpring', medium: 'trueAutumn', deep: 'deepAutumn' } },
  cool: { bright: { light: 'brightWinter', medium: 'trueWinter', deep: 'deepWinter' }, soft: { light: 'lightSummer', medium: 'trueSummer', deep: 'softSummer' }, blended: { light: 'lightSummer', medium: 'trueSummer', deep: 'deepWinter' } },
  neutral: { bright: { light: 'brightSpring', medium: 'brightSpring', deep: 'brightWinter' }, soft: { light: 'softSummer', medium: 'softSummer', deep: 'softAutumn' }, blended: { light: 'softSummer', medium: 'softAutumn', deep: 'softAutumn' } }
};

function getSeason(a) {
  const axes = computeColorAxes(a);
  return { key: SEASON_TABLE[axes.undertone][axes.chroma][axes.value], axes };
}

function getPremiumBucket(axes) {
  return axes.value === 'deep' ? 'deep' : axes.undertone;
}

const SEASON_FAMILY = { lightSpring: 'spring', trueSpring: 'spring', brightSpring: 'spring', lightSummer: 'summer', trueSummer: 'summer', softSummer: 'summer', softAutumn: 'autumn', trueAutumn: 'autumn', deepAutumn: 'autumn', brightWinter: 'winter', trueWinter: 'winter', deepWinter: 'winter' };

const archetypesBySeasonFamily = {
  spring: { apple: 'Soft and Unbothered', pear: "She's Just Built Different", hourglass: 'The It Girl', rectangle: 'The Vibe Curator', inverted: 'Boss Energy' },
  summer: { apple: 'Confident and Clean', pear: 'Quietly Iconic', hourglass: 'Sleek and Stunning', rectangle: 'The Minimalist', inverted: 'Cool Girl Season' },
  autumn: { apple: 'Chic on Her Terms', pear: "Soft but Make it Chef's Kiss", hourglass: 'Timeless and That Girl', rectangle: "She Don't Miss", inverted: 'Strong and Stunning' },
  winter: { apple: 'Bold and Beautiful', pear: 'Rich Girl Energy', hourglass: 'Unapologetically Her', rectangle: 'The Statement', inverted: 'Powerful and Polished' }
};

const proportionTips = {
  petite: { longTorso: "Keep hemlines above the knee and reach for high-rise bottoms — this shortens the torso visually and lengthens the leg line, which matters most on a petite frame.", longLegs: "You can wear longer hemlines and midi lengths beautifully — the main thing to watch is oversized volume, which can overwhelm a petite frame fast.", balanced: "Most standard hem lengths will already work for you — a good tailor taking things in to your exact height is the single highest-impact thing you can do." },
  average: { longTorso: "High-rise bottoms and slightly cropped tops help balance a longer torso — a belt sitting right at your natural waist does a lot of the work here.", longLegs: "Midi and maxi lengths are especially flattering on you — you can wear proportions a lot of people can't pull off.", balanced: "You can wear nearly any hem length or rise comfortably — dress to the occasion rather than to the proportion." },
  tall: { longTorso: "Look for tops with a little extra body length and high-rise bottoms so the waistline doesn't sit too low on you.", longLegs: "Maxi lengths, wide-leg trousers and longline blazers all read intentional and elegant rather than overwhelming on your frame.", balanced: "Nearly every silhouette reads elongated and put-together on your frame — this is a genuine advantage, lean into it." }
};

const colorData = {
  lightSpring: { undertone: 'Light Spring', label: 'Light Spring', desc: 'A warm undertone with light, delicate coloring. This client glows in warm colors kept light and clear — not deep, not muted.', metal: 'Light Gold / Champagne — brighter gold reads better than antique or deep gold', neutrals: [{n:'Ivory',h:'#f5efe0'},{n:'Camel',h:'#d4b896'},{n:'Light Warm Gray',h:'#c9c0b3'},{n:'Soft Peach Beige',h:'#e8d4bc'}], signature: [{n:'Peach',h:'#f4a97f'},{n:'Coral',h:'#ef8354'},{n:'Light Aqua',h:'#8fd3c8'},{n:'Warm Yellow',h:'#f2c14e'},{n:'Apple Green',h:'#9bc25c'},{n:'Light Turquoise',h:'#6fc7c0'}], accents: [{n:'Champagne Gold',h:'#d9c48a'},{n:'Light Coral',h:'#f2967a'},{n:'Aqua',h:'#7fd4c9'}], accessory: 'Bags — camel, ivory, light tan. Shoes — warm nude, light tan, coral. Jewelry — light/champagne gold always. Belts — light tan leather.', patterns: ['Light warm florals and watercolor prints', 'Small-to-medium scale prints in warm, clear colors', 'Soft tropical or botanical prints', 'Avoid heavy, dark, or busy large-scale prints'], avoid: 'Black, deep burgundy, icy pastels, and gray — all too heavy or cool for this light warm palette.' },
  trueSpring: { undertone: 'True Spring', label: 'True Spring', desc: 'A classic warm undertone with clear, medium-depth coloring. This client thrives in vivid, golden-based warm colors.', metal: 'Gold — bright, warm gold is the most flattering metal', neutrals: [{n:'Camel',h:'#c8a882'},{n:'Warm Ivory',h:'#f2ead8'},{n:'Golden Brown',h:'#8a6240'},{n:'Warm Khaki',h:'#b9a978'}], signature: [{n:'Coral',h:'#f2704b'},{n:'Golden Yellow',h:'#f0b429'},{n:'Grass Green',h:'#6fae44'},{n:'Turquoise',h:'#29a89a'},{n:'Warm Red',h:'#e0472b'},{n:'Tangerine',h:'#f2884b'}], accents: [{n:'Gold',h:'#c9a96e'},{n:'Bright Coral',h:'#f2704b'},{n:'Turquoise',h:'#29a89a'}], accessory: 'Bags — camel, cognac, warm brown. Shoes — warm-toned nude, tan, coral. Jewelry — gold always. Belts — cognac leather.', patterns: ['Bold warm florals and tropical prints', 'Medium-to-large scale prints', 'Tortoiseshell and warm animal prints'], avoid: 'Black, icy pastels, cool gray, mauve, and silver-based tones.' },
  brightSpring: { undertone: 'Bright Spring', label: 'Bright Spring', desc: 'Vivid, high-clarity coloring that sits between spring warmth and winter brightness. This client glows in saturated, clean colors — never muted or dusty.', metal: 'Gold or Bright Silver — either works as long as it is bright, not antiqued', neutrals: [{n:'Bright White',h:'#fbfbfb'},{n:'Warm Charcoal',h:'#3f3a38'},{n:'Camel',h:'#c9a882'},{n:'True Navy',h:'#223350'}], signature: [{n:'Hot Pink',h:'#ec1f6a'},{n:'Turquoise',h:'#14b8a6'},{n:'Bright Coral',h:'#f2543d'},{n:'Lemon Yellow',h:'#f2d13f'},{n:'Grass Green',h:'#55b02e'},{n:'Bright Periwinkle',h:'#4d6fe0'}], accents: [{n:'Gold',h:'#c9a96e'},{n:'Fuchsia',h:'#d4087a'},{n:'Bright Aqua',h:'#1fc6c6'}], accessory: 'Bags — bright white, camel, true navy, statement color. Shoes — white, bright color, warm nude. Jewelry — bright gold or bright silver. Belts — camel or navy.', patterns: ['Bold graphic prints and color-blocking', 'High-contrast patterns', 'Clean geometric prints'], avoid: 'Muted or dusty tones, beige-on-beige, and anything pastel-soft or washed out.' },
  lightSummer: { undertone: 'Light Summer', label: 'Light Summer', desc: 'A cool undertone with a delicate, airy quality. This client is flattered by soft, light cool colors — never deep or vivid ones.', metal: 'Silver or Rose Gold — soft, light metals only', neutrals: [{n:'Soft White',h:'#f4f2ee'},{n:'Light Gray',h:'#b9bdc4'},{n:'Powder Blue-Gray',h:'#a9b8c4'},{n:'Taupe',h:'#b7ada3'}], signature: [{n:'Powder Pink',h:'#eab8bf'},{n:'Periwinkle',h:'#9aa8d8'},{n:'Soft Lavender',h:'#b6a3cf'},{n:'Soft Aqua',h:'#9fcfd0'},{n:'Dusty Rose',h:'#c98fa0'},{n:'Sky Blue',h:'#a7cbe0'}], accents: [{n:'Silver',h:'#c7c9cc'},{n:'Soft Pink',h:'#eab8bf'},{n:'Lavender',h:'#b6a3cf'}], accessory: 'Bags — soft gray, blush, soft white. Shoes — cool nude, soft gray, blush. Jewelry — silver or soft rose gold. Belts — soft taupe or gray.', patterns: ['Soft watercolor florals', 'Delicate small-scale prints', 'Low-contrast tone-on-tone patterns'], avoid: 'Black, orange, mustard, and deep rich tones — all too heavy for this light cool palette.' },
  trueSummer: { undertone: 'True Summer', label: 'True Summer', desc: 'A classic cool undertone with soft, muted, medium-depth coloring. This client is flattered by dusty, blue-based colors rather than warm or high-contrast ones.', metal: 'Silver — the most flattering metal for this palette', neutrals: [{n:'Cool Gray',h:'#9aa0a6'},{n:'Navy',h:'#33465e'},{n:'Soft White',h:'#f0f0ee'},{n:'Taupe Rose',h:'#baa3a0'}], signature: [{n:'Dusty Rose',h:'#c98a91'},{n:'Soft Burgundy',h:'#8f4a56'},{n:'Lavender',h:'#9c88c4'},{n:'Powder Blue',h:'#9bb8d3'},{n:'Sage',h:'#93a68c'},{n:'Mauve',h:'#a97c8a'}], accents: [{n:'Silver',h:'#c0c0c0'},{n:'Rose',h:'#c98a91'},{n:'Soft Plum',h:'#7d5a75'}], accessory: 'Bags — navy, gray, soft rose. Shoes — cool-toned nude, navy, gray. Jewelry — silver always. Belts — navy or gray.', patterns: ['Soft muted florals', 'Tone-on-tone patterns', 'Gentle geometric prints'], avoid: 'Orange, warm gold, black, and bright neon — too warm or too harsh.' },
  softSummer: { undertone: 'Soft Summer', label: 'Soft Summer', desc: 'A cool-neutral undertone with a soft, muted quality. This client glows in dusty, blended colors — best avoiding both very bright and very warm tones.', metal: 'Silver or Pewter — brushed, not shiny', neutrals: [{n:'Taupe',h:'#a99e93'},{n:'Soft Gray',h:'#9b9691'},{n:'Dusty Navy',h:'#3e4a5c'},{n:'Greige',h:'#b0a89c'}], signature: [{n:'Dusty Teal',h:'#5b8a86'},{n:'Mauve',h:'#9a6b73'},{n:'Soft Plum',h:'#77566e'},{n:'Muted Rose',h:'#bd8b8f'},{n:'Sage Green',h:'#8a9a7e'},{n:'Slate Blue',h:'#6e7f96'}], accents: [{n:'Pewter',h:'#9a9a9a'},{n:'Muted Rose',h:'#bd8b8f'},{n:'Dusty Teal',h:'#5b8a86'}], accessory: 'Bags — taupe, dusty navy, greige. Shoes — muted rose, taupe, gray. Jewelry — brushed silver or pewter. Belts — taupe leather.', patterns: ['Muted tone-on-tone prints', 'Soft blended florals'], avoid: 'Bright neon, pure black, orange, and high-contrast color blocking.' },
  softAutumn: { undertone: 'Soft Autumn', label: 'Soft Autumn', desc: 'A warm-neutral undertone with a soft, muted quality. This client is flattered by dusty earthy colors — never bright or icy ones.', metal: 'Soft Gold or Bronze — brushed, matte finishes', neutrals: [{n:'Warm Taupe',h:'#a68f74'},{n:'Soft Camel',h:'#c2a480'},{n:'Warm Gray',h:'#948575'},{n:'Mushroom',h:'#b4a690'}], signature: [{n:'Sage Green',h:'#8a9a6b'},{n:'Dusty Coral',h:'#c98a6b'},{n:'Warm Olive',h:'#7d7a4a'},{n:'Soft Rust',h:'#b56a4a'},{n:'Muted Gold',h:'#b99a55'},{n:'Terracotta',h:'#b96a4e'}], accents: [{n:'Bronze',h:'#a97848'},{n:'Soft Gold',h:'#c2a35c'},{n:'Dusty Coral',h:'#c98a6b'}], accessory: 'Bags — camel, olive, warm taupe. Shoes — warm muted nude, camel, olive. Jewelry — bronze or soft gold. Belts — camel or olive leather.', patterns: ['Muted botanical prints', 'Soft plaid', 'Tone-on-tone earthy prints'], avoid: 'Icy pastels, pure black, bright fuchsia, and stark white.' },
  trueAutumn: { undertone: 'True Autumn', label: 'True Autumn', desc: 'A classic warm undertone with rich, earthy, medium-to-deep coloring. This client thrives in warm, grounded colors with real depth.', metal: 'Gold or Bronze — richer, warmer golds especially', neutrals: [{n:'Camel',h:'#b98a55'},{n:'Chocolate Brown',h:'#5c3d24'},{n:'Warm Olive',h:'#6e6b3f'},{n:'Cream',h:'#ede0c8'}], signature: [{n:'Rust',h:'#b5541f'},{n:'Mustard',h:'#c99a2e'},{n:'Forest Green',h:'#3f6b3f'},{n:'Pumpkin',h:'#d1732a'},{n:'Warm Brown',h:'#7a4a2a'},{n:'Teal',h:'#2f6b63'}], accents: [{n:'Gold',h:'#c9a05a'},{n:'Copper',h:'#b06a35'},{n:'Olive',h:'#6e6b3f'}], accessory: 'Bags — cognac, chocolate brown, olive. Shoes — warm-toned nude, cognac, brown. Jewelry — gold or bronze. Belts — cognac leather.', patterns: ['Rich botanical and animal prints', 'Plaid', 'Medium-to-large scale warm prints'], avoid: 'Icy pastels, black, cool gray, bubblegum pink, and silver.' },
  deepAutumn: { undertone: 'Deep Autumn', label: 'Deep Autumn', desc: 'A warm undertone with deep, rich coloring. This client is flattered by deep, saturated warm colors that match natural depth — never pale or icy ones.', metal: 'Gold or Copper — deep, rich tones', neutrals: [{n:'Chocolate Brown',h:'#4a3220'},{n:'Deep Olive',h:'#4f4f2c'},{n:'Espresso',h:'#3a2a1e'},{n:'Warm Charcoal',h:'#3c332c'}], signature: [{n:'Deep Rust',h:'#9c3f1e'},{n:'Burnt Orange',h:'#b5541f'},{n:'Deep Teal',h:'#1f5c56'},{n:'Bronze',h:'#8a5a2e'},{n:'Deep Gold',h:'#b5892e'},{n:'Burgundy',h:'#6e2430'}], accents: [{n:'Copper',h:'#b06a35'},{n:'Deep Gold',h:'#b5892e'},{n:'Bronze',h:'#8a5a2e'}], accessory: 'Bags — espresso, dark brown, deep jewel tone. Shoes — cognac, dark brown, bold color. Jewelry — gold or copper. Belts — dark brown leather.', patterns: ['Rich deep botanical prints', 'High-contrast warm patterns', 'Animal print'], avoid: 'Pale pastels, icy tones, silver, and light gray — all too pale for this deep warm palette.' },
  brightWinter: { undertone: 'Bright Winter', label: 'Bright Winter', desc: 'A cool-neutral undertone with vivid, high-clarity coloring. This client comes alive in saturated jewel tones and high-contrast combinations.', metal: 'Silver or White Gold — bright, clean metals', neutrals: [{n:'Bright White',h:'#fafafa'},{n:'True Black',h:'#191919'},{n:'Charcoal',h:'#322f2e'},{n:'Icy Gray',h:'#cfd3d6'}], signature: [{n:'Fuchsia',h:'#d4087a'},{n:'Emerald',h:'#0e8a5e'},{n:'True Red',h:'#d21f2c'},{n:'Royal Blue',h:'#1e4fd6'},{n:'Hot Pink',h:'#ec1f6a'},{n:'Ice Blue',h:'#7fd1e0'}], accents: [{n:'Silver',h:'#c7c9cc'},{n:'Fuchsia',h:'#d4087a'},{n:'Emerald',h:'#0e8a5e'}], accessory: 'Bags — black, white, jewel tone. Shoes — black, white, bold color. Jewelry — silver. Belts — black leather.', patterns: ['Bold high-contrast prints', 'Color-blocking', 'Graphic prints'], avoid: 'Muted earth tones, orange, warm camel, and dusty pastels.' },
  trueWinter: { undertone: 'True Winter', label: 'True Winter', desc: 'A classic cool undertone with deep, clear coloring. This client is flattered by icy or jewel-toned colors with strong, cool clarity.', metal: 'Silver or Platinum — the coolest, brightest metals', neutrals: [{n:'True Black',h:'#171717'},{n:'Pure White',h:'#fbfbfb'},{n:'Charcoal',h:'#2e2e2e'},{n:'Navy',h:'#16233b'}], signature: [{n:'Emerald',h:'#0d7a52'},{n:'Sapphire',h:'#164fa3'},{n:'True Red',h:'#c8102e'},{n:'Royal Purple',h:'#4b1e78'},{n:'Icy Pink',h:'#e6a6c7'},{n:'Fuchsia',h:'#c2126b'}], accents: [{n:'Silver',h:'#c0c0c0'},{n:'Sapphire',h:'#164fa3'},{n:'Icy Pink',h:'#e6a6c7'}], accessory: 'Bags — black, navy, jewel tone. Shoes — black, navy, white. Jewelry — silver or platinum. Belts — black leather.', patterns: ['High-contrast graphic prints', 'Black-and-white', 'Bold color-blocking'], avoid: 'Warm earth tones, orange, mustard, camel, and muted/dusty colors.' },
  deepWinter: { undertone: 'Deep Winter', label: 'Deep Winter', desc: 'A cool undertone with deep, rich coloring. This client is flattered by deep saturated colors with cool undertones — never muted or pastel shades.', metal: 'Silver or Platinum — deep jewel tones with cool metals', neutrals: [{n:'True Black',h:'#141414'},{n:'Deep Charcoal',h:'#2a2a2a'},{n:'Pure White',h:'#f7f7f7'},{n:'Deep Navy',h:'#101c33'}], signature: [{n:'Deep Burgundy',h:'#5e1526'},{n:'Forest Green',h:'#123d2a'},{n:'Sapphire',h:'#123a7a'},{n:'Deep Purple',h:'#3a1450'},{n:'True Red',h:'#b3122a'},{n:'Deep Fuchsia',h:'#8a0f52'}], accents: [{n:'Silver',h:'#c0c0c0'},{n:'Deep Burgundy',h:'#5e1526'},{n:'Sapphire',h:'#123a7a'}], accessory: 'Bags — black, deep jewel tone. Shoes — black, deep color. Jewelry — silver or platinum. Belts — black leather.', patterns: ['Bold deep-toned prints', 'High-contrast prints'], avoid: 'Pastels, muted earth tones, orange, and light beige.' }
};

const premiumColorData = {
  warm: { seasonal: ['Spring — warm pastels: blush with yellow undertone, peach, warm mint, soft coral', 'Summer — lean into terracotta, coral, warm white, olive green', 'Autumn — this is your strongest season: camel, burnt orange, mustard, forest green', 'Winter — deep warm tones: burgundy with warm undertone, forest green, rich cognac brown'], makeup: ['Lip colors — warm reds, terracotta, peach, coral, brick', 'Eye colors — warm browns, copper, bronze, gold, olive green shadow', 'Blush — peach, warm coral, apricot', 'Foundation — look for warm, golden or yellow undertone, never pink or cool beige'], hair: ['Highlights — honey, golden, caramel, auburn, copper', 'Lowlights — rich warm brown, chestnut, coffee tones', 'Colors to avoid — ash, platinum, blue-black, these fight natural warmth'], foundation: 'Look for foundations labeled warm, golden, yellow, peach or beige. Avoid labels that say cool, pink or rosy. Test on jawline in natural light.' },
  cool: { seasonal: ['Spring — icy pastels: pale blue, soft lavender, cool mint', 'Summer — cool brights: cobalt, fuchsia, emerald', 'Autumn — cool versions: plum, cool burgundy, teal, skip warm oranges', 'Winter — this is your strongest season: deep jewel tones, black, bright white, icy silver'], makeup: ['Lip colors — cool reds, berry, plum, mauve, cool pink', 'Eye colors — silver, gray, cool taupe, navy liner, purple shadow', 'Blush — cool pink, soft rose, berry tones', 'Foundation — look for cool, pink or neutral undertone, never warm or golden'], hair: ['Highlights — platinum, ash blonde, cool brown, icy highlights', 'Lowlights — cool dark brown, ash, cool espresso tones', 'Colors to avoid — warm golden, honey, copper, red tones'], foundation: 'Look for foundations labeled cool, pink, rosy or neutral when it looks pink-toned. Avoid labels that say warm, golden or yellow.' },
  neutral: { seasonal: ['Spring — soft dusty pastels: blush, sage, soft lavender, dusty peach', 'Summer — muted brights: dusty rose, sage green, warm mauve, dusty blue', 'Autumn — warm neutrals: taupe, camel, dusty rose with warm accessories', 'Winter — deep muted tones: warm wine, deep sage, warm charcoal'], makeup: ['Lip colors — dusty rose, warm mauve, soft berry, nude with warm undertone', 'Eye colors — taupe, warm brown, rose gold, soft bronze, dusty pink', 'Blush — warm peach, soft rose, dusty pink', 'Foundation — both warm and cool toned can work, test in natural light'], hair: ['Highlights — honey or ash both work, choose based on preference', 'Lowlights — warm brown or cool brown both complement', 'Rose gold, auburn or warm ash all work well'], foundation: 'Look for foundations labeled neutral, balanced or beige without a strong warm or cool pull. Test both a warm and cool shade on the jawline.' },
  deep: { seasonal: ['Spring — jewel tones work year round, fuchsia and cobalt are especially striking', 'Summer — bold brights: fuchsia, cobalt, citrus yellow, hot coral', 'Autumn — burnt orange, deep gold, ruby red, warm cognac', 'Winter — deep purple, emerald, royal blue, bright white'], makeup: ['Lip colors — bold berry, deep plum, ruby red, bright coral, warm terracotta', 'Eye colors — gold, copper, bronze, deep rich brown, jewel-toned liner', 'Blush — deep rose, warm berry, rich peach', 'Foundation — look for rich deep tones with warm or neutral undertone, avoid anything ashy'], hair: ['Highlights — honey, copper, auburn, warm golden', 'Lowlights — deep espresso, rich dark brown, blue-black', 'Silver and gray hair against deep skin reads especially striking'], foundation: 'Look for foundations with rich deep coverage and a warm or neutral undertone. Avoid foundations that look gray or ashy. Always test in natural daylight.' }
};

const bodyData = {
  apple: { shape: 'Apple Shape', desc: 'Weight carried in the midsection with slimmer legs and less defined waist.', goal: 'Create the illusion of a defined waist while drawing attention to beautiful legs and neckline.', sils: ['A-line dresses and skirts', 'Empire waist styles', 'Wrap dresses in flowy fabrics', 'Fit and flare silhouettes', 'Maxi dresses with a defined waistline'], tops: ['V-necks and deep scoop necks', 'Off shoulder styles', 'Flowy tops that skim the body', 'Structured blazers worn open', 'Peplum tops'], bots: ['Wide leg trousers in dark colors', 'Straight leg pants in dark colors', 'A-line midi skirts', 'Flowy maxi skirts'], acc: ['Statement earrings', 'Long necklaces', 'Simple belts worn just under the bust', 'Heels'], avd: ['Tight fitted tops that cling around the midsection', 'Cropped tops that end at the belly', 'Belts cinched at the natural waist', 'Bodycon dresses'], fabGood: 'Structured woven fabrics — cotton, linen and ponte. Flowy chiffon and georgette for tops.', fabAvoid: 'Clingy jersey and spandex around the midsection. Satin and silk that highlight the midsection.', shopKeywords: 'wrap dress, A-line dress, empire waist, flowy top, V-neck blouse, wide leg pants, midi A-line skirt' },
  pear: { shape: 'Pear Shape', desc: 'Narrower shoulders and bust with fuller hips and thighs. Beautifully defined waist.', goal: 'Balance the silhouette by drawing attention to the upper body and highlighting the defined waist.', sils: ['A-line skirts and dresses', 'Wrap dresses that define the waist', 'Fit and flare dresses', 'High waisted wide leg trousers'], tops: ['Boat necks and wide scoop necks', 'Off shoulder and cold shoulder tops', 'Bold prints and bright colors on top', 'Statement collars', 'Puff sleeves'], bots: ['Wide leg trousers in dark solid colors', 'A-line skirts in any length', 'Flowy midi skirts', 'Dark wash straight leg jeans'], acc: ['Statement necklaces and earrings', 'Bold scarves or statement collars', 'Belts at natural waist'], avd: ['Clingy fabrics on hips and thighs', 'Horizontal stripes on the bottom half', 'Pencil skirts and bodycon', 'Skinny jeans with fitted tops'], fabGood: 'Structured fabrics on bottom — denim, ponte, thick cotton. Flowy and textured fabrics on top.', fabAvoid: 'Clingy jersey on hips and thighs. Satin or shiny fabrics below the waist.', shopKeywords: 'A-line dress, wrap dress, wide leg trousers, off shoulder top, bold print blouse, puff sleeve top' },
  hourglass: { shape: 'Hourglass Shape', desc: 'Balanced bust and hips with a beautifully defined waist. Almost every silhouette works.', goal: 'Celebrate and highlight natural curves and defined waist.', sils: ['Wrap dresses', 'Fit and flare dresses', 'Belted styles in any silhouette', 'Pencil skirts with a fitted top'], tops: ['Wrap tops', 'V-necks that follow the body naturally', 'Fitted and tailored tops', 'Button down shirts tied at the waist'], bots: ['High waisted everything', 'Pencil skirts and midi skirts', 'Wide leg and straight leg trousers'], acc: ['Belts, worn whenever possible', 'Statement jewelry in any style'], avd: ['Boxy oversized shapes that hide the waist', 'Drop waist styles', 'Shapeless shift dresses'], fabGood: 'Almost everything works — stretchy fabrics that follow curves, structured wovens, wrap and draped fabrics.', fabAvoid: 'Very stiff boxy fabrics that fight the curves.', shopKeywords: 'wrap dress, fitted dress, belted dress, high waisted jeans, pencil skirt, fit and flare, tailored blazer' },
  rectangle: { shape: 'Rectangle Shape', desc: 'Measurements are similar throughout. Athletic build with less defined waist.', goal: 'Create curves and waist definition through silhouette, layering and strategic details.', sils: ['Peplum tops and dresses', 'Belted styles', 'Fit and flare dresses', 'Wrap dresses and tops'], tops: ['Peplum tops', 'Ruffles and embellishments', 'Crop tops with high waisted bottoms', 'Strategic layering — blazers and jackets'], bots: ['Full and A-line skirts', 'Wide leg trousers with a fitted belted top', 'Pleated skirts'], acc: ['Wide belts at the natural waist', 'Statement earrings and necklaces', 'Layered jewelry'], avd: ['Straight shift dresses with no shape', 'Boxy silhouettes with no definition', 'Dropped waist styles'], fabGood: 'Structured fabrics that add shape — ponte, thick cotton, denim. Fabrics with texture.', fabAvoid: 'Very soft drapey fabrics with no structure.', shopKeywords: 'peplum top, peplum dress, belted dress, fit and flare dress, wrap dress, ruffled skirt, A-line skirt' },
  inverted: { shape: 'Inverted Triangle Shape', desc: 'Broader shoulders and fuller bust with narrower hips.', goal: 'Balance the strong upper body by drawing attention downward and adding volume to hips and legs.', sils: ['Wide leg trousers with a simple top', 'A-line and flared skirts', 'Fit and flare dresses', 'Maxi skirts with volume'], tops: ['V-necks and scoop necks', 'Simple halter necks', 'Dark solid colors on top', 'Simple fitted tees with statement bottoms'], bots: ['Bold prints and bright colors on bottom', 'Wide leg and flared trousers', 'Full and A-line skirts'], acc: ['Long pendant necklaces', 'Hip bags and belt bags', 'Ankle boots and statement shoes'], avd: ['Boat necks and very wide necklines', 'Shoulder pads and puff sleeves', 'Strapless styles that emphasize shoulders'], fabGood: 'Flowy fabrics on the bottom — chiffon, georgette, flared denim. Simple structured fabrics on top.', fabAvoid: 'Stiff structured fabrics on top that add shoulder width.', shopKeywords: 'wide leg pants, flared trousers, A-line skirt, tiered skirt, bold print skirt, V-neck top' }
};

module.exports = {
  computeColorAxes,
  getSeason,
  getPremiumBucket,
  SEASON_FAMILY,
  archetypesBySeasonFamily,
  proportionTips,
  colorData,
  premiumColorData,
  bodyData
};
